wanna-go-home/lens_review_android

app/build.gradle, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiClient.kt, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiInterface.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/Article.kt, app/src/main/java/com/wannagohome/lens_review_android/support/di/ViewModelModule.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/BoardViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/BoardListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/TabBoard.kt, app/src/main/res/layout/article_list_item.xml, app/src/main/res/layout/fragment_board.xml, app/src/main/res/layout/fragment_search.xml
=> Board detail

app/src/main/java/com/wannagohome/lens_review_android/ui/lens_detail/LensDetailActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/lens_detail/LensDetailViewModel.kt, app/src/main/res/layout/activity_detailed_lens.xml
렌즈 디테일 api 부착완료.
ui 없음. 단순 정보표시
=> lens detail api without UI

app/build.gradle, app/src/main/java/com/wannagohome/lens_review_android/network/AppRetrofitBuilder.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/MainActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/ArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/BoardListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/TabBoard.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/lens_detail/LensDetailActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/login/LoginActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/ReviewDetailActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_list/ReviewListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_list/TabReview.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/write/WriteReviewActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/search_lens/LensListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/search_lens/TabSearch.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/signup/SignUpActivity.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties
kotlin 버전 업데이트로 인한 뷰 바인딩 변경
okHttp 버전 업데이트
gradle버전 업데이트
resolve wanna-go-home/Issue#21
=> kotlin new version migration

app/src/main/AndroidManifest.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_sign_up.xml
=> disable enter

app/src/main/res/drawable/primary_button_enabled.xml, app/src/main/res/drawable/primary_button_enabled_pressed.xml, app/src/main/res/drawable/selector_primary_button.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_sign_up.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
resolve wanna-go-home/Issue#47
=> color & button style

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiClient.kt, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiInterface.kt, app/src/main/java/com/wannagohome/lens_review_android/support/di/ViewModelModule.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/TabBoard.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/ArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/ArticleViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/MoreDialog.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/modify/ModifyArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/modify/ModifyArticleViewModel.kt, app/src/main/res/layout/activity_article.xml, app/src/main/res/layout/activity_modify_article.xml, app/src/main/res/layout/fragment_dialog_option.xml, app/src/main/res/values/strings.xml
resolve wanna-go-home/Issue#23
생각해보니까 깊이 알려준 Shared View Model로 안해서 재사용불가;; 
코멘트 CRUD하면서 재사용해야해서 그때 하겠음 
@rlarlvy153 deleteSuccess => finish() 왜 안 돼는지 좀 바주셈 ㅠ
=> add freeboard delete/modify actions and add option modal in article

app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/comment/CommentActivity.kt
ㅈㅅ 아묻따 머지좀 ㅎ; 내가 잘못했다!
resolve https://github.com/wanna-go-home/Issue/issues/70
=> resolve comment activity abnormal behavior

.circleci/config.yml, app/src/main/res/values-round/strings.xml
fix https://github.com/wanna-go-home/Issue/issues/49
- 안드로이드 빌드를 위한 CircleCI적용
- 우리 플랜 정보임. 안드만 CircleCi 쓰면 크레딧 걱정은 없을듯 일단
=> CircleCI 적용

app/src/main/AndroidManifest.xml, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiClient.kt, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiInterface.kt, app/src/main/java/com/wannagohome/lens_review_android/support/di/ViewModelModule.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/MainViewPagerAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/ArticleListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/BoardViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/TabArticle.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/ArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/ArticleViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/MoreDialog.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/comment/CommentActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/comment/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/comment/CommentViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/modify/ModifyArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/modify/ModifyArticleViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/write/WriteArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/write/WriteArticleViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/mypage/TabMypage.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/mypage/myarticle/MyArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/mypage/myarticle/MyArticleViewModel.kt, app/src/main/res/layout/activity_modify_article.xml, app/src/main/res/layout/activity_my_article.xml, app/src/main/res/layout/activity_write_article.xml
resolve wanna-go-home/Issue#41
내가 쓴 글 리스트 액티비티
오른쪽으로 열리고 닫힘
그외
board -> article 변수변경
@up0617 title bar 사용법 참고 ㄱ
=> 내가 쓴 글 리스트

app/build.gradle, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiClient.kt, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiInterface.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/article/Article.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/article/ArticlePreview.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/article/Comment.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/article/WriteArticleRequest.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/article/WriteCommentRequest.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/comment/CommentViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/BoardListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/BoardViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/TabBoard.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/ArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/ArticleViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/comment/CommentActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/comment/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/comment/CommentViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/modify/ModifyArticleViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/mypage/myarticle/MyArticleViewModel.kt, app/src/main/res/layout/activity_article.xml, app/src/main/res/layout/activity_comment.xml, app/src/main/res/layout/child_comment_list_item.xml, app/src/main/res/layout/comment_list_item.xml, app/src/main/res/layout/fragment_board.xml, app/src/main/res/values-round/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
resolve https://github.com/wanna-go-home/Issue/issues/79
resolve https://github.com/wanna-go-home/Issue/issues/81
1. 보드 / 아티클 / 코멘트 액티비티 각각 리프레시 적용
- 이 과정에서 linear layout을 constraints layout으로 일부 변경함
2. 코멘트 / 차일드코멘트 작성 적용
3. 작성 후 리프레시 적용 (go to bottom X)
4. 글씨크기 등 ui 조금 수정함
=> Write comment / add refresh

app/src/main/java/com/wannagohome/lens_review_android/network/model/article/ArticlePreview.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/ArticleListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/comment/CommentActivity.kt, app/src/main/res/layout/activity_article.xml, app/src/main/res/layout/activity_comment.xml, app/src/main/res/layout/activity_write_article.xml, app/src/main/res/layout/child_comment_list_item.xml, app/src/main/res/layout/comment_list_item.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
코멘트가 안나오던 문제를 해결하고(Relative view 없애서 그랬음) 
UI를 좀 정리함. 좀 더 깔끔해졌을것임.
=> Write comment

app/src/main/java/com/wannagohome/lens_review_android/network/model/article/ArticlePreview.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/ArticleListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/TabArticle.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/ArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/comment/CommentActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/modify/ModifyArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/article/write/WriteArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/login/LoginActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_list/TabReview.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/signup/SignUpActivity.kt, app/src/main/res/layout/activity_article.xml, app/src/main/res/layout/activity_comment.xml, app/src/main/res/layout/activity_write_article.xml, app/src/main/res/layout/article_list_item.xml, app/src/main/res/layout/child_comment_list_item.xml, app/src/main/res/layout/comment_list_item.xml, app/src/main/res/layout/fragment_dialog_option.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
으으 모달하기 싫어서 자꾸 이상한것만 하고잇음 
resolve https://github.com/wanna-go-home/Issue/issues/90
resolve https://github.com/wanna-go-home/Issue/issues/91
=> Comment crud

app/src/main/java/com/wannagohome/lens_review_android/ui/review/write/SelectLensFragment.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/write/WriteReviewViewModel.kt
=> write review

app/src/main/AndroidManifest.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/fragment_write_review.xml, app/src/main/res/values/strings.xml
=> write review ui error resolve

app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiClient.kt, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiInterface.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/user/ModifyNicknameRequest.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/MainActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/mypage/MypageViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/mypage/TabMypage.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_list/ReviewListAdapter.kt, app/src/main/res/layout/dialog_modify_nickname.xml, app/src/main/res/values/strings.xml
resolve wanna-go-home/Issue#43
=> Modify nickname

app/src/main/java/com/wannagohome/lens_review_android/network/model/article/Article.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/comment/Comment.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/review/Review.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/BottomSheetFragment.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/ArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/ArticleViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/comment/ArticleCommentViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/comment/CommentActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/comment/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/list/ArticleListAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/ReviewDetailActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/ReviewDetailViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/comment/CommentActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/comment/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/comment/ReviewCommentViewModel.kt, app/src/main/res/layout/activity_article.xml, app/src/main/res/layout/article_list_item.xml, app/src/main/res/layout/child_comment_list_item.xml, app/src/main/res/layout/comment_list_item.xml, app/src/main/res/values/strings.xml
resolve https://github.com/wanna-go-home/Issue/issues/104
isAuthor 구현을 반영함
작성자 여부에 따라 수정/삭제 아니면 신고 버튼이 활성화되는데 
신고는 일단 "신고가 되었습니다" 토스트만 띄워놓고 동작은 없는 상태임. 
신고버튼 있는 4군데를 수정하니까 개짜침; 일단 릴리즈 전에 좋아요 만들어놓고 템플릿메서드로 변경하던, 템플릿메서드로 바꾸고 좋아요 구현하던 하겟삼
=> Apply is author

app/build.gradle, app/src/main/java/com/wannagohome/lens_review_android/ui/MainViewPagerAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/list/TabArticle.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/mypage/TabMypage.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_list/TabReview.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/search_lens/TabSearch.kt
닉수정 앱종료 후 GC 되지않은 싱글턴 instance 및 viewModel이 남아있어서 새로 객체만들기로 수정
resolve wanna-go-home/Issue#173
=> 앱종료 후 닉네임 수정 에러 수정

app/src/main/java/com/wannagohome/lens_review_android/ui/signup/SignUpActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/signup/TermsActivity.kt, app/src/main/res/layout/activity_terms.xml, app/src/main/res/values/strings.xml
resolve wanna-go-home/Issue#169
=> term titlebar

app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/ArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/comment/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/ReviewDetailActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/comment/CommentAdapter.kt
resolve https://github.com/wanna-go-home/Issue/issues/168
댓글 액티비티가 오른쪽에서 열림
바인드에 있던 코드를 인잇 시점으로 넘겨줌. 
다른 것들도 작업했는데 74번 PR에 잇음
=> Comment Activity From Right

app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/ArticleActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/comment/CommentActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/article/detail/comment/CommentAdapter.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/ReviewDetailActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/comment/CommentActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/review/review_detail/comment/CommentAdapter.kt, app/src/main/res/layout/activity_article.xml, app/src/main/res/layout/activity_review_detail.xml, app/src/main/res/layout/comment_list_item.xml
resolve https://github.com/wanna-go-home/Issue/issues/143
https://github.com/wanna-go-home/lens_review_android/pull/73 
73번 머지하구 머지 ㄱㄱ
=> Remove onclick from binding

app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiClient.kt, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiInterface.kt, app/src/main/java/com/wannagohome/lens_review_android/network/model/user/CheckDuplicateResponse.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/signup/SignUpActivity.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/signup/SignUpViewModel.kt, app/src/main/res/values/strings.xml
휴대폰 중복체크 추가
체크 리스폰스 모델 변경
resolve wanna-go-home/Issue#175
=> Check duplicate

app/src/main/java/com/wannagohome/lens_review_android/network/AppRetrofitBuilder.kt, app/src/main/java/com/wannagohome/lens_review_android/network/InterceptorManager.kt, app/src/main/java/com/wannagohome/lens_review_android/network/lensapi/LensApiClient.kt, app/src/main/java/com/wannagohome/lens_review_android/support/AccessKeyHelper.kt, app/src/main/java/com/wannagohome/lens_review_android/support/di/NetworkModule.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/mypage/MypageViewModel.kt, app/src/main/java/com/wannagohome/lens_review_android/ui/signup/SignUpViewModel.kt
resolve wanna-go-home/Issue#174
=> Minir issue

app/src/main/res/layout/activity_article.xml, app/src/main/res/layout/activity_comment.xml, app/src/main/res/layout/activity_review_detail.xml
disable https://github.com/wanna-go-home/Issue/issues/186
=> Diable camera btn

app/build.gradle
=> edit server address
